### ISSUE TITLE
YouTube playlists don't play

### ISSUE THREAD

**Issue by Itz-Hyperz** [doamatto/5m_loading#7] opened 2020-12-17 14:53 UTC
**Describe the bug**
I cannot get the music to play from a YouTube playlist.

**To Reproduce**
1. Go to Start the resource
2. Click on Connect to your server
3. No music plays, and no options to play / pause come up.
4. Press F8

**Expected behavior**
I expected it to play the music from the YouTube Playlist I put in.

**Screenshots**
This is the error I get: 
![F8 Console Error](https://user-images.githubusercontent.com/69090660/102502937-37566380-404d-11eb-95c7-914e99d4b9fe.png)
![HTML file](https://user-images.githubusercontent.com/69090660/102503342-9f0cae80-404d-11eb-8cb7-55d27551b78d.png)
![JS File](https://user-images.githubusercontent.com/69090660/102503397-b186e800-404d-11eb-97ca-01402e6155da.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by doamatto** [comment] 2020-12-17 16:54
I hear you loud and clear. To say the least, this is a pretty major bug. As it mentions in the logs, `SC` is undefined. This was a common issue when developing and I could have sworn I squashed the bug. However, I'll work towards resolving it. If possible, try opening the `loadscreen.html` in your web browser, seeing if it works there, and take a screenshot of the console by pressing `Ctrl`+`Shift`+`J` (the console of the web browser).

In the meantime, I'll see if I can't reproduce further and get towards resolving this issue. Just to double-check, what version of this loading screen are you using?

**Comment by doamatto** [comment] 2020-12-17 17:10
I did have a similar issue and may have fixed it. Can you downloading the latest version from the `master` branch and using that? Lmk if there are any issues.

**Comment by doamatto** [comment] 2020-12-19 16:07
[A similar issue](https://forum.cfx.re/t/release-5mloading-yet-another-loading-screen/1459768/21?u=doamatto) was posted on the forum. They said the `master` branch patch had [fixed the issue.](https://forum.cfx.re/t/release-5mloading-yet-another-loading-screen/1459768/26?u=doamatto) Can you let me know if you're still having issues? If I don't hear back, I'll close the issue in 5 days or so (but feel free to let me know to re-open it if needed)

**Comment by Itz-Hyperz** [comment] 2020-12-19 22:53
I'll give it a test!

**Comment by doamatto** [comment] 2021-01-03 16:09
Since it's been 15 days since I've last heard and I got good feedback off the FiveM forums, I'm going to be closing this issue and tagging a release. Feel free to let me know otherwise, of course!

**Closed by doamatto** 2021-01-03 16:09 UTC
Labels: bug
